[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'npm ci',
    'cd server && npm ci',
    'cd client && npm ci'
]

[phases.build]
cmds = [
    'npm run build'
]

[start]
cmd = 'npm start'
