[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'cd server && npm ci --production'
]

[phases.build]
cmds = [
    'cd client && npm ci && npm run build'
]

[start]
cmd = 'cd server && npm start'
