[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'npm ci --prefix server',
    'npm ci --prefix client'
]

[phases.build]
cmds = [
    'npm run build --prefix client'
]

[start]
cmd = 'node server/server.js'
